name: flask_login_template
dependencies:
  - python=3.10
  - pip
  - pip:
      - Flask-Migrate==3.1.0
      - Flask-Login==0.6.2
      - itsdangerous==2.0.1
      - Flask-Mail==0.9.1
      - Flask-WTF==0.15.1
      - python-dotenv==0.21.0
      - psycopg2-binary==2.9.5
      - email-validator==1.2.1